format:
  revealjs:
    theme: default
    css: styles.css
    slide-number: true
    progress: true
    hash: true
    center: false
    navigation-mode: linear
    title-slide-attributes:
      data-background-color: "#13294B"
    include-in-header:
      - _partials/header.html
    include-after-body:
      - _partials/footer.html

execute:
  echo: false


